import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Target Vault Directory to copy files to
const VAULT_PLUGIN_DIR = "C:/Users/jugri/Documents/My Vault/.obsidian/plugins/ai-ocr-formatter";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    await copyFiles();
    process.exit(0);
} else {
    await context.watch();
    // Simple watch mechanism to copy on rebuild could be added here, 
    // but for now we'll just rely on manual build or 'dev' script usage.
    // For this environment, we usually just run build once.
}

async function copyFiles() {
    if (!fs.existsSync(VAULT_PLUGIN_DIR)) {
        console.log("Vault directory not found, skipping copy.");
        return;
    }

    const filesToCopy = ["main.js", "manifest.json", "styles.css"];

    for (const file of filesToCopy) {
        if (fs.existsSync(file)) {
            fs.copyFileSync(file, path.join(VAULT_PLUGIN_DIR, file));
            console.log(`Copied ${file} to vault.`);
        }
    }
}
